<a href="https://colab.research.google.com/github/joyangelai/Colabs-Vol-2/blob/main/Feature_Scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder

In [ ]:
df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

# NORMALIZATION

In [ ]:
scaler = MinMaxScaler()
df_scaled = scaler.fit_transform(df[['total_bill']])
df_scaled[:5]

array([[0.29157939],
       [0.1522832 ],
       [0.3757855 ],
       [0.43171345],
       [0.45077503]])

In [ ]:
nr_tip = scaler.fit_transform(df[['tip']])
nr_tip[:5]

array([[0.00111111],
       [0.07333333],
       [0.27777778],
       [0.25666667],
       [0.29      ]])

# STANDARDIZATION

In [ ]:
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df[['total_bill']])
df_scaled[:5]

array([[-0.31471131],
       [-1.06323531],
       [ 0.1377799 ],
       [ 0.4383151 ],
       [ 0.5407447 ]])

In [ ]:
df['time'].unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

# ENCODING

In [ ]:
# load data set
data = sns.load_dataset("titanic")
data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
data['class'].unique()

['Third', 'First', 'Second']
Categories (3, object): ['First', 'Second', 'Third']

In [ ]:
enc = OneHotEncoder()
class_en = enc.fit_transform(data[['class']])
class_en

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 891 stored elements and shape (891, 3)>