<a href="https://colab.research.google.com/github/joyangelai/Colabs-Vol-2/blob/main/MPG_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import necessary libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, r2_score, mean_squared_error, mean_absolute_error, root_mean_squared_error

In [ ]:
# load dataset
df = pd.read_csv("/content/homeprices (1).csv")
df.head()

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

Observation: Data is uniform from top to bottom

In [ ]:
dataset= sns.get_dataset_names()
print(dataset, end=" ")

['anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'dowjones', 'exercise', 'flights', 'fmri', 'geyser', 'glue', 'healthexp', 'iris', 'mpg', 'penguins', 'planets', 'seaice', 'taxis', 'tips', 'titanic']

In [ ]:
df2 = sns.load_dataset("mpg")
df2.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [ ]:
df2.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [ ]:
df3 = df2[['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year']]
df3.head()

    mpg  cylinders  displacement  horsepower  weight  acceleration  model_year
0  18.0          8         307.0       130.0    3504          12.0          70
1  15.0          8         350.0       165.0    3693          11.5          70
2  18.0          8         318.0       150.0    3436          11.0          70
3  16.0          8         304.0       150.0    3433          12.0          70
4  17.0          8         302.0       140.0    3449          10.5          70

In [ ]:
#  checking null values
df3.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
dtype: int64

In [ ]:
# dropping null values
df3.dropna(inplace=True)

<ipython-input-13-157660837>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.dropna(inplace=True)

In [ ]:
# check null values again
df3.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
dtype: int64

In [ ]:
# divide features and target
X = df3.drop('mpg', axis=1)
X.head()
y =  df3['mpg']
y.head()

0    18.0
1    15.0
2    18.0
3    16.0
4    17.0
Name: mpg, dtype: float64

In [ ]:
# check shape
df3.shape

(392, 7)

In [ ]:
# splitting dataset to train and test
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=42, test_size=0.2)

In [ ]:
X_train.shape

(313, 6)

In [ ]:
X_test.shape

(79, 6)

In [ ]:
y_train.shape

(313,)

In [ ]:
y_test.shape

(79,)

In [ ]:
# scaling the dataset
scale = StandardScaler()
X_train_s =scale.fit_transform(X_train)
X_test_s = scale.transform(X_test)

In [ ]:
# creating model & fitting
model = LinearRegression()
model.fit(X_train_s, y_train)

LinearRegression()

In [ ]:
# checking coeff
model.coef_

array([-0.19723011,  0.10499657, -0.08700746, -5.5098621 ,  0.17368415,
        2.75679957])

In [ ]:
# y intercept
model.intercept_

np.float64(23.599361022364224)

In [ ]:
# making predictions
y_pred = model.predict(X_test_s)

In [ ]:
# cheking accuracy
score = r2_score(y_pred, y_test)
print(round(score*100,2),"%")

80.37 %

In [ ]:
mean_squared_error(y_pred,y_test)

10.502370329417298

In [ ]:
mean_absolute_error(y_pred, y_test)  # --> not the best way to do it

2.5038600897761243

In [ ]:
# doing root mean squared error
root_mean_squared_error(y_pred,y_test)

3.240736078334257