<a href="https://colab.research.google.com/github/joyangelai/Colabs-Vol-2/blob/main/SQL_basic2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/chinook.db")
df3 = pd.read_sql("""SELECT firstname, lastname, Title, city
                     FROM employees""", conn)
df3.head()

  FirstName LastName                Title      City
0    Andrew    Adams      General Manager  Edmonton
1     Nancy  Edwards        Sales Manager   Calgary
2      Jane  Peacock  Sales Support Agent   Calgary
3  Margaret     Park  Sales Support Agent   Calgary
4     Steve  Johnson  Sales Support Agent   Calgary

In [ ]:
# using pipes to combine firstname and lastname
conn = sqlite3.connect("/content/chinook.db")
df4 = pd.read_sql("""SELECT firstname || ' ' || lastname as FullName, Title, city
                     FROM employees""", conn)
df4.head()

        FullName                Title      City
0   Andrew Adams      General Manager  Edmonton
1  Nancy Edwards        Sales Manager   Calgary
2   Jane Peacock  Sales Support Agent   Calgary
3  Margaret Park  Sales Support Agent   Calgary
4  Steve Johnson  Sales Support Agent   Calgary

In [ ]:
# select names starting with ste
conn = sqlite3.connect("/content/chinook.db")
dfa= pd.read_sql("""SELECT firstname, Title, city
                     FROM employees
                     WHERE firstname LIKE 'Ste%'
                      """, conn)
dfa.head()

  FirstName                Title     City
0     Steve  Sales Support Agent  Calgary

In [ ]:
# select names ending with ve
conn = sqlite3.connect("/content/chinook.db")
dfa= pd.read_sql("""SELECT firstname, Title, city
                     FROM employees
                     WHERE firstname LIKE '%ve'
                      """, conn)
dfa.head()

  FirstName                Title     City
0     Steve  Sales Support Agent  Calgary

In [ ]:
# selecting from calgary city
conn = sqlite3.connect("/content/chinook.db")
dfb= pd.read_sql("""SELECT firstname, Title, city
                     FROM employees
                     WHERE city LIKE '%Calgary%'
                      """, conn)
dfb.head()

  FirstName                Title     City
0     Nancy        Sales Manager  Calgary
1      Jane  Sales Support Agent  Calgary
2  Margaret  Sales Support Agent  Calgary
3     Steve  Sales Support Agent  Calgary
4   Michael           IT Manager  Calgary

In [ ]:
# selecting from calgary city using in operator
conn = sqlite3.connect("/content/chinook.db")
dfc= pd.read_sql("""SELECT firstname, Title, city
                     FROM employees
                     WHERE city IN ('Calgary', 'Lethbridge')
                      """, conn)
dfc

  FirstName                Title        City
0     Nancy        Sales Manager     Calgary
1      Jane  Sales Support Agent     Calgary
2  Margaret  Sales Support Agent     Calgary
3     Steve  Sales Support Agent     Calgary
4   Michael           IT Manager     Calgary
5    Robert             IT Staff  Lethbridge
6     Laura             IT Staff  Lethbridge

In [ ]:
# checking unique cities in ascending order(ASC) and decscending order (DESC)
dfz= pd.read_sql("""SELECT DISTINCT (city)
                     FROM employees
                     ORDER BY city ASC
                      """, conn)
dfz.head()

         City
0     Calgary
1    Edmonton
2  Lethbridge

In [ ]:
# using group by
dfy= pd.read_sql("""SELECT BillingCity, COUNT(CustomerId) as total_count
                     FROM invoices
                     GROUP BY BillingCity
                     HAVING COUNT(Customerid) > 7
                     ORDER BY Billingcity ASC
                      """, conn)
dfy

     BillingCity  total_count
0         Berlin           14
1         London           14
2  Mountain View           14
3          Paris           14
4         Prague           14
5      São Paulo           14

In [ ]:
#--inner join
#SELECT tr.Name, al.Title
#FROM tracks tr

#INNER JOIN albums al  ON tr.AlbumId = al.AlbumId;

In [ ]:
# SELECT Title as albumTitle,
#         (SELECT COUNT(Trackid)
#         FROM tracks
#         WHERE albumid = albums.AlbumId) as tranaccc
# FROM albums
# LIMIT 5;

In [ ]:
# # using subquery on WHERE clause
# dfz= pd.read_sql("""SELECT DISTINCT (city)
#                      FROM employees
#                      ORDER BY city ASC
#                       """, conn)
# dfz.head()

In [ ]:
# SELECT customerId, FirstName || ' ' || LastName as FullName
# FROM customers
#     WHERE customerid IN(SELECT CustomerId
#     FROM invoices
#     GROUP BY CustomerId
#     HAVING COUNT(invoiceId) > 5);

In [ ]:
# COMMON TABLE EXPRESSION(CTE)